### ISSUE TITLE
Destroying the clusters containing new LSF created VMs

### ISSUE THREAD

**Issue by marconetto** [IBM-Cloud/hpc-cluster-lsf#6]
According to the documentation below, in order to destroy the cluster all VMs created by LSF should be destroyed first.  Is there a best practice to do so?

I'm building a DevOps pipeline that requires full automation for creating and destroying LSF clusters. I've noticed for instance that the subnets that were created by terraform cannot be destroyed  because of the VMs created by LSF in which terraform I guess has no visibility.

https://cloud.ibm.com/docs/ibm-spectrum-lsf?topic=ibm-spectrum-lsf-deleting-resources&interface=cli

**Comment by AugieMena3** [comment]
Yes, it is necessary that VMs created by LSF itself must be destroyed prior to issuing the destroy command for the cluster via Schematics.  As you noted, Terraform is not aware of the state of the VMs created by LSF.

**Comment by marconetto** [comment]
Is there any official script to  delete all those VMs created by LSF (from outside LSF)?

**Comment by AugieMena3** [comment]
The VMs created by the LSF auto-scaling feature (Resource Connector) should ideally get deleted by LSF after remaining idle for some time once jobs running on those have been completed.  You can check what LSF nodes (VMs) exist by running `bhosts -w.`  If for some reason, LSF does not delete dynamic nodes which it created, you can use the IBM Cloud CLI to delete them yourself:
`ibmcloud is instance-delete <instance_id> --force`

**Comment by marconetto** [comment]
bhosts -w will return the list of all nodes.... in order to delete the dynamic nodes, I need to get the list of only nodes created after the original provisioning.... not sure if such command exists. Does it?

I can think about ways to figure that out. Such as, once a cluster is provisioned, I keep the list of the original nodes in a file. Then I compare with bhosts with the file to find out the dynamic nodes. Another way could be to check the uptime of all nodes and those outside a range could be the dynamic ones...

**Comment by AugieMena3** [comment]
As you noted, `bhosts -w` lists all of the nodes, both static and dynamic.

But, yes, the ways you mention to figure out which ones are the dynamic nodes as opposed to the static nodes should work.

**Comment by AugieMena3** [comment]
Closing given clarification provided above seems to have been sufficient.
