### ISSUE TITLE
LSF REST API access

### ISSUE THREAD

**Issue by marconetto** [IBM-Cloud/hpc-cluster-lsf#7]
I would like to work with the LSF clusters provisioned by the terraform scripts via RESTFul APIs.  Do these terraform scripts + image allow me to do that or some extra configuration / installation is necessary?

For instance, I'm having trouble to find some files (e.g. ``pac_api.py`` or ``pacclient.py``) described by
https://www.ibm.com/docs/en/slac/10.1.0?topic=services-requirements

**Comment by georgeg000** [comment]
the LSF App Center sample client has been opened source in this location:
https://github.com/IBMSpectrumComputing/lsf-integrations/tree/master/Spectrum%20LSF%20Application%20Center/pacclient

**Comment by AugieMena3** [comment]
Closing this given that Application Center support has been added as noted above since the issue was originally opened.
